### ISSUE TITLE
Does not appear to work in Light Table 0.6.7

### ISSUE THREAD

**Issue by crinklywrappr** [davecoates/lt-relativelinenumbers#1]
FYI.  I've tried this in both :editor and :editor.active.  (:lt.plugins.relativelinenumbers/relative-linenumber-settings false true)

**Comment by davecoates** [comment]
It appears to work for me with:

{:+ { 
  :editor.active [
(:lt.plugins.relativelinenumbers/relative-linenumber-settings false true)
 ]
}}

Are you getting any error messages in the console?

**Comment by crinklywrappr** [comment]
No error messages in the console.  Tried on two different PCs.  Maybe you can tell me what is wrong if I give you my entire User Behaviors.

```
{:+ {
     :app [(:lt.objs.style/set-skin "dark")
           (:lt.objs.sidebar.workspace/workspace.open-on-start)]

     :editor [:lt.objs.editor/no-wrap
              :lt.plugins.trail-whitespace/show-trailing-whitespace
              (:lt.objs.style/set-theme "default")
              (:lt.plugins.vim/activate-vim)
              (:lt.objs.editor/tab-settings true 4 4)]

     :editor.active [(:lt.plugins.relativelinenumbers/relative-linenumber-settings false true)]

     :editor.clojure [(:lt.plugins.clojure/print-length 1000)]}

 :- {:app [:lt.objs.intro/show-intro]}}
```

**Comment by crinklywrappr** [comment]
Maybe I'm doing something wrong on the editor as well.  I test the following situations
1. command mode
2. command mode w/ relative lines toggled
3. insert mode w/ relative lines toggled
4. insert mode

**Comment by Driphter** [comment]
Do you have line-numbers enabled? If not, try adding `:lt.objs.editor/line-numbers` to your user behaviors.

**Comment by davecoates** [comment]
Closing this, if you think there's still an issue please reopen
