### ISSUE TITLE
Screen not scrolling with cursor

### ISSUE THREAD

**Issue by Driphter** [davecoates/lt-relativelinenumbers#2]
When I move the cursor below the bottom of the screen, the screen doesn't scroll with the cursor.

Removing `(.refresh (editor/->cm-ed this))` from the `::update-line-numbers` behavior fixes the scrolling, but breaks the line-numbers.

I'm currently using the following hack to update the gutter, but there has to be a better way:

``` clojure
(behavior ::update-line-numbers
          :triggers #{:move :active}
          :reaction (fn [this]
                      (let [last-line (-> @state :pos :line)]
                        (swap! state assoc :pos (editor/->cursor this))
                        (when (not= last-line (-> @state :pos :line))
                          (let [ln-option (editor/option this "lineNumbers")
                                ln-option (and ln-option (or (= ln-option "t") "t"))]
                            (editor/set-options this {"lineNumbers" ln-option}))))))
```

**Comment by davecoates** [comment]
Thanks - should be fixed; my solution was to always scroll into view
