### ISSUE TITLE
Scroll-position does not follow cursor

### ISSUE THREAD

**Issue by hkjels** [davecoates/lt-relativelinenumbers#3]

**Comment by crantok** [comment]
I have the same issue.

To reproduce:
- Install plugin
- Open a file that is 3 times too long to be shown in its entirety
- Press PgDn repeatedly

What you see:
- Line number displayed at bottom right of LT increases
- Page does not scroll (until you've paged to the final line of the file.)

To correct behaviour:
- Uninstall plugin
- Restart LT

Light Table version
0.7.2
Binary version
0.8.6

**Comment by crantok** [comment]
Fixed for me.

LT's plugin manager installs the 0.1.0 version, not the latest packaged version (0.1.1). Installing manually fixed the problem.

**Comment by davecoates** [comment]
Thanks for that - I've now submitted 0.1.1 to plugin-metadata repo. Will close this when added

**Comment by davecoates** [comment]
Can now install 0.1.1 from light table plugin repo
