### ISSUE TITLE
Line numbers not shown

### ISSUE THREAD

**Issue by crantok** [davecoates/lt-relativelinenumbers#4]
After installing the plugin, no functionality seems to be added. No line numbers (relative or absolute) are shown. I've tried using the command menu to select relative line numbers but nothing happened.

Light Table version
0.7.2
Binary version
0.8.6

**Comment by crantok** [comment]
Manually upgraded to the 0.1.1 version of the plugin. This is still broken for me.

**Comment by crantok** [comment]
Fixed for me.

Line numbers have to be enabled manually in order to use this plugin. I looked in the command menu and saw no line number options so thought there was nothing to do. Solved the problem by adding

```
[:editor :lt.objs.editor/line-numbers]
```

to my "Settings: User behaviors" file.

**Comment by davecoates** [comment]
Thanks, updated readme with instructions
